---
- name: tao vlan
  hosts: all
  gather_facts: no

  tasks:
    - name: Thêm cổng vào vlan
    ios_vlan:
      vlan_id: 100
      interfaces:
        - Et0/1
        - Et0/2
        - Et0/3  

    - name: Show vlan
      ios_command:
        commands:
          - show vlan brief
      register: show_vlan

    - debug: var=show_vlan.stdout_lines
